apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: pipelines-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Pipelines
      name: pipelines.openaihub.ibm.com
      version: v1alpha1
  description: Placeholder description
  displayName: Pipelines Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - pods
          - pods/exec
          - pods/log
          - services
          - deployments
          - replicasets
          - namespaces
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - create
          - delete
        - apiGroups:
          - argoproj.io
          resources:
          - workflows
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - metacontroller.k8s.io
          resources:
          - compositecontrollers
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - kubeflow.org
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - pipelines-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - extensions
          resources:
          - ingresses
          - podsecuritypolicies
          - deployments
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - openaihub.ibm.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - app.k8s.io
          resources:
          - applications
          verbs:
          - '*'
        serviceAccountName: pipelines-operator
      deployments:
      - name: pipelines-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: pipelines-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: pipelines-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: ffdlops/kfp:v0.0.1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: pipelines-operator
                - name: KUBEFLOW_TAG
                  value: fcb9839
                image: ffdlops/kfp:v0.0.1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: pipelines-operator
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
