apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    description: Pipelines
    containerImage: ffdlops/kfp:v0.0.3
    alm-examples: |
      [{}]
  name: pipelines-operator.v0.1.0
  namespace: kubeflow
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Pipelines
      name: pipelines.pipelines.ibm.com
      version: v1alpha1
      displayName: Pipelines CRD
      description: The Pipelines CRD
  description: Placeholder description
  displayName: Pipelines Operator
  links: 
  - name: code
    url: https://github.com/adrian555/pipelines-operator
  maintainers: 
  - name: Weiqiang Zhuang
    email: wzhuang@us.ibm.com
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - pipelines
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - pipelines.ibm.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: pipelines
      deployments:
      - name: pipelines
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: pipelines
          strategy: {}
          template:
            metadata:
              labels:
                name: pipelines
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: ffdlops/kfp:v0.0.3
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: pipelines
                image: ffdlops/kfp:v0.0.3
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: pipelines
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.0
