apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pipelines-operator
  template:
    metadata:
      labels:
        name: pipelines-operator
    spec:
      serviceAccountName: pipelines-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: ffdlops/kfp:v0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: ffdlops/kfp:v0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pipelines-operator"
            - name: KUBEFLOW_TAG
              value: "fcb9839"
      volumes:
        - name: runner
          emptyDir: {}
