apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pipelines
  template:
    metadata:
      labels:
        name: pipelines
    spec:
      serviceAccountName: pipelines
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "ffdlops/kfp:v0.0.3"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "ffdlops/kfp:v0.0.3"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pipelines"
      volumes:
        - name: runner
          emptyDir: {}
