apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pipelines-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - pods
  - pods/exec
  - pods/log
  - services
  - deployments
  - replicasets
  - namespaces
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - "snapshot.storage.k8s.io"
  resources:
  - volumesnapshots
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - "argoproj.io"
  resources:
  - workflows
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - metacontroller.k8s.io
  resources:
  - compositecontrollers
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
  verbs:
  - '*'
- apiGroups:
  - "kubeflow.org"
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - pipelines-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  - podsecuritypolicies
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - openaihub.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - '*'
