- name: Check whether ks exists
  stat:
    path: /opt/ansible/ks
  register: ks_stats

- name: Download ksonnet
  block:
    - get_url: 
        url: https://github.com/ksonnet/ksonnet/releases/download/v{{ pipelines.ks_version }}/ks_{{ pipelines.ks_version }}_linux_amd64.tar.gz
        dest: "{{ pipelines.kubeflow_src }}/ks.tgz"
    - shell: |
        tar zxvf {{ pipelines.kubeflow_src }}/ks.tgz
    - copy:
        src: "ks_{{ pipelines.ks_version }}_linux_amd64/ks"
        dest: "/opt/ansible/ks"
        mode: 0744    
  when: ks_stats.stat.exists == False           
