- name: create temporary kubeflow src dir
  file: path="{{ pipelines.kubeflow_src }}" state=directory

- name: get PATH
  shell: echo $PATH
  register: path

- name: download ks
  include: ks.yml

- name: download kubectl
  include: kubectl.yml

- name: Check whether kubeflow folders exists
  stat:
    path: "{{ pipelines.kubeflow_src }}/kubeflow"
  register: kubeflow_stats

- name: extract kubeflow folders
  block:
    - shell: |
        cd {{ pipelines.kubeflow_src }}
        tar zxvf /opt/ansible/patched/custom-kubeflow.tgz
  when: kubeflow_stats.stat.exists == False

- name: set up and generate k8s application
  ignore_errors: yes
  environment:
    DEFAULT_KUBEFLOW_COMPONENTS: "{{ pipelines.components }}"
    K8S_NAMESPACE: "{{ pipelines.namespace }}"
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    cd {{ pipelines.kubeflow_src }}
    scripts/kfctl.sh init kfapp --platform none
    cd kfapp
    ../scripts/kfctl.sh generate k8s
  when: kubeflow_stats.stat.exists == False

- name: hack to set up specific environment etc
  environment:
    DEFAULT_KUBEFLOW_COMPONENTS: "{{ pipelines.components }}"
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    cd {{ pipelines.kubeflow_src }}/kfapp/ks_app
    ks param set ambassador ambassadorServiceType NodePort
    ks param set argo containerRuntimeExecutor pns
    ks param set argo executorImage tomcli/argoexec:containerd
    ks param set argo workflowControllerImage tomcli/workflow-controller:containerd
  when: kubeflow_stats.stat.exists == False

- name: deploy kubeflow pipelines service
  ignore_errors: yes
  environment:
    DEFAULT_KUBEFLOW_COMPONENTS: "{{ pipelines.components }}"
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    cd {{ pipelines.kubeflow_src }}/kfapp
    ../scripts/kfctl.sh apply k8s

- name: wait for service running
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    state=""
    retries=0
    while [ "$state" != "Running" -a $retries -lt 300 ]
    do
        sleep 2
        retries=`expr $retries + 1`
        state=$(kubectl get pods -o=jsonpath='{range .items[*]}{.status.phase}{"\n"}{end}' -n {{ pipelines.namespace }} |uniq)
    done
