- name: create temporary kubeflow src dir
  file: path="{{ pipelines.kubeflow_src }}" state=directory

- name: get PATH
  shell: echo $PATH
  register: path

- name: download ks
  include: ks.yml

- name: download kubectl
  include: kubectl.yml

- name: Check whether download.sh exists
  stat:
    path: "{{ pipelines.kubeflow_src }}/download.sh"
  register: kubeflow_stats

- name: download kubeflow scripts
  block:
    - get_url: 
        url: https://raw.githubusercontent.com/kubeflow/kubeflow/{{ pipelines.kubeflow_tag }}/scripts/download.sh
        dest: "{{ pipelines.kubeflow_src }}/download.sh"
    - shell: |
        cd {{ pipelines.kubeflow_src }}
        bash download.sh
  when: kubeflow_stats.stat.exists == False

- name: set up and generate k8s application
  ignore_errors: yes
  environment:
    DEFAULT_KUBEFLOW_COMPONENTS: "{{ pipelines.components }}"
    K8S_NAMESPACE: "{{ pipelines.namespace }}"
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    cd {{ pipelines.kubeflow_src }}
    scripts/kfctl.sh init kfapp --platform none
    cd kfapp
    ../scripts/kfctl.sh generate k8s
  when: kubeflow_stats.stat.exists == False

- name: hack to set up specific environment etc
  environment:
    DEFAULT_KUBEFLOW_COMPONENTS: "{{ pipelines.components }}"
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    cd {{ pipelines.kubeflow_src }}/kfapp/ks_app
    ks param set ambassador ambassadorServiceType {{ pipelines.ambassador_service_type }}
    ks param set argo containerRuntimeExecutor {{ pipelines.container_runtime_executor }}
    ks param set argo uiImage {{ pipelines.ui_image }}
    ks param set argo executorImage {{ pipelines.executor_image }}
    ks param set argo workflowControllerImage {{ pipelines.workflow_controller_image }}
  when: kubeflow_stats.stat.exists == False

- name: deploy kubeflow pipelines service
  ignore_errors: yes
  environment:
    DEFAULT_KUBEFLOW_COMPONENTS: "{{ pipelines.components }}"
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    cd {{ pipelines.kubeflow_src }}/kfapp
    ../scripts/kfctl.sh apply k8s

- name: wait for service running
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    state=""
    retries=0
    while [ "$state" != "Running" -a $retries -lt 300 ]
    do
        sleep 2
        retries=`expr $retries + 1`
        state=$(kubectl get pods -o=jsonpath='{range .items[*]}{.status.phase}{"\n"}{end}' -n {{ pipelines.namespace }} |uniq)
    done
